## PROJECT 2 & 3

In [ ]:
with open('login.txt','x') as f:
    pass                      #creating a login text file

In [3]:
import login
id,pw =login.display()
with open('login.txt','r') as f:
    for line in f:
        text = line.split()
        if(id==text[0] and pw==text[1]):
            print("Successfully Validate.\n")
            if id=='admin':
                import admin
                break
            else:
                import employee
                with open('hr.txt','r') as hr:     #checking if login id is of hr
                    for line in hr:
                        lst=line.strip().split('|')
                        flag=False
                        if(lst[0]==id):
                            flag= True
                            break
                    if(flag==False):
                        employee.emp_login(id)
                        break
                    else:
                        employee.hr_login(id)
                        break
    else:
        print("Invalid id and password.")

Welcome to Employee System
Please enter login id : 7
please enter password : rahul
Successfully Validate.

Welcome RAHUL DAS from HR !!

Enter 1 to view own details.
Enter 2 to view all employee
Enter q to exit.

Enter your Choice: 1

Employee id : 2
Name : shruti mahato
Date of joining : 12/12/2020
Designation : software developer
Salary : 400000.0


Employee id : 3
Name : megha mahato
Date of joining : 2/3/2004
Designation : web developer
Salary : 400000.0


Employee id : 5
Name : mukta mahato
Date of joining : 3/6/2012
Designation : assistant manager
Salary : 70000.0


Employee id : 6
Name : rishabh raj
Date of joining : 4/6/2014
Designation : front end developer
Salary : 60000.0


Employee id : 7
Name : rahul das
Date of joining : 4/3/2002
Designation : software engineer
Salary : 500000.0


Employee id : 8
Name : shree priya
Date of joining : 2/4/2014
Designation : jr. software engineer
Salary : 300000.0


Employee id : 9
Name : aanchal verma
Date of joining : 2/4/2001
Designation : creative director
Salary : 80000.0

Welcome RAHUL DAS from HR !!

Enter 1 to view own details.
Enter 2 to view all employee
Enter q to exit.

Enter your Choice: 2
Enter the designation : software engineer

Employee id : 7
Name : rahul das
Date of joining : 4/3/2002
Designation : software engineer
Salary : 500000.0

Welcome RAHUL DAS from HR !!

Enter 1 to view own details.
Enter 2 to view all employee
Enter q to exit.

Enter your Choice: q